### PR TITLE
Specify the command through a `command` file instead of a parameter.

### PR DESCRIPTION
**Pull request by SamirTalwar**
@codecop, could you give this branch a shot and let me know what you think?

### CODE REVIEW

**Comment by codecop** [comment]
Sorry for late reply, esp. after you already did the change. I will test it later on Windows. 

I already see that not all tests will run on Windows out of the box. Is this something we have to live with it? Or do we create another test set and have the tests duplicated for Win and *nix?

Also it feels that the command file makes things more complex to use. I liked the easy usage of just providing the command. Maybe the command file could be optional? Just thinking loud here.

**Comment by SamirTalwar** [comment]
How about choosing between a *command* file and a `--command` switch? The latter would only work with simple commands (i.e. no spaces).

**Comment by codecop** [comment]
that sounds reasonable. So everything would kind of work like before and the command file is an extended option for more complex command invocations.

**Comment by SamirTalwar** [comment]
Ideally, yes!

Also, I would really like the tests to pass on Windows too. However, it might require disabling some, such as anything depending on executable Ruby scripts (which we could minimise, but not remove altogether, as it's a feature that needs to be tested).

**Comment by codecop** [comment]
The only way when these tests run using Windows and Linux at the same time would be to force creation of a wrapper script, e.g. `testcase` (bash) and `testcase.bat` for each test. Then the call to "testcase" would work on both platforms the same as long as both scripts are provided. This is how `smoke` and `smoke.bat` work - and it works nicely. I remember you proposing this and me not being in favour of this option ;-) The wrapper would be the same as the command file, just executable, so the same amount of extra work needed.

Still this all feels more cumbersome than helpful for the users of Smoke. I do not believe we want to add code for different platforms into Smoke if we can help it.

**Comment by codecop** [comment]
Samir, for completeness, here are the changes necessary to run the full testsuite now: https://github.com/codecop/Smoke/commit/ec751abba9de78e2e43e5ae3248da06bd6aa8d59
The addition of ruby in several places is expected, but the last two changes hurt because the file check is not aware of Windows extensions that can be omitted. I would have to provide exact names like `a.exe` or `b,bat` which is usually not done.

**Comment by SamirTalwar** [comment]
I am surprised you need to specify the *.bat* suffix, @codecop. Could you check your `PATHEXT` environment variable contains ".bat"?

The [`validate_application`](https://github.com/SamirTalwar/Smoke/pull/5/files#diff-2512775486864c0a64eaa2cf491f0aebR57) method should be reading that and using it.

**Comment by codecop** [comment]
Thank you for teaching me about `PATHEXT` - I did not know about that. Yes it contains all these.
`PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW`
Interestingly it contains `.RB` as well and I can run plain Ruby scripts in the shell, who knew? Weird that it does not work in Smoke though.

Regarding the `smoke.bat` - I assume it is because there is also a `smoke` file and it is found but it is not executable.

**Comment by SamirTalwar** [comment]
Perhaps you should consider just running [Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about). 😉

**Comment by codecop** [comment]
I had a zsh from UnxUtils working fine before 64bit era :-(

**Pull request merged**
